CFLAGS = -Wall, -g

ex15:	ex15.c
	gcc ex15.c -o ex15

ex15-e:	ex15-e.c
	gcc ex15-e.c -o ex15-e

argument:	argument.c
	gcc argument.c -o argument

rwp:	rwp.c
	gcc rwp.c -o rwp

clean:
	rm -f ex15 ex15-e argument rwp
